# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x', '8.0.x' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Display dotnet version
      run: dotnet --version
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build the project
      run: dotnet build --configuration Release --no-restore
      
    - name: Run test
      run: dotnet test --configuration Release --no-build --verbosity normal
